name: Release
on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
      - release/[0-9]+.[0-9]+.x

jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
      - name: Match LMS Release
        uses: ./.github/actions/match-lms-release
        with:
          RALLY_API_KEY: ${{ secrets.RALLY_API_KEY }}
          GITHUB_TOKEN: foo
          NPM: true
          NPM_TOKEN: foo
          DRY_RUN: true
